config/routes.rb
Rails.application.routes.draw do
  post "/" => 'flights#show' , as: 'forma'
  post "/user/select_fly", to: 'flights#select_fly' , as: 'select_fly', via: [:get, :post]
  root 'flights#index'
  post "/user/new", to: 'flights#user_new' , as: 'users'
  post "/user/add", to: 'flights#user_add' , as: 'user_add'
  post "/pay", to: 'flights#pay' , as: 'pay'

  # post "/user_admin", to: 'flights#user_admin' , as: "user_admin"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :user_bookings
  has_many :users, through: :user_bookings
  
  belongs_to :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  has_many :bookings

  has_many :user_flights
  has_many :users, through: :user_flights
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_bookings
  has_many :bookings, through: :user_bookings
  #has_many :flights, through: :bookings
  has_many :user_flights
  has_many :flights, through: :user_flights

  validates :name, presence: true
  validates :email, presence: true, email: true


end

app/models/user_booking.rb
class UserBooking < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/user_flight.rb
class UserFlight < ApplicationRecord
  belongs_to :user
  belongs_to :flight
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @fligths = Flight.all
  end

  def show
    p "´" * 50
    origen = params[:flow][:flight_origin]
    destino = params[:flow][:flight_destiny]
    año_selected = params[:calendar]["date(1i)"]
    mes_selected = params[:calendar]["date(2i)"]
    dia_selected = params[:calendar]["date(3i)"]
    seats_selected = params[:flow][:seats_selected].to_i
    flights = []
    @flights = Flight.where(origin: origen, destiny: destino, total_seats: (seats_selected..40)).each do |flight|
       flights << flight
    end

    if @flights.empty?
      @no_vuelos = "Reinicia la busqueda"
    else
      #p "-" * 50
      flights.delete_if do |flight|
         año_selected.to_i != flight.depart.year
         mes_selected.to_i != flight.depart.month
         dia_selected.to_i != flight.depart.day
        #p "Año seleccionado #{año_selected.to_i} en igual a Año de vuelo #{ flight.depart.year}: #{año_selected.to_i == flight.depart.year}"
      end
       @flights = flights
       @seats_selected = seats_selected
    end
    p "´" * 50
  end

  def select_fly
    p "." * 50
    p "SELECT FLY"
    @seats_selected = params[:seats_selected]
    @flight_seleceted = Flight.find_by(id: params[:flight_id])
    $seats = @seats_selected.to_i
    $flight =  @flight_seleceted
    @booking = Booking.create!( flight_id: @flight_seleceted.id, total_cost: ($seats * $flight.cost))
    $booking = @booking
    p "." * 50
  end

  def user_add
    p "-" * 50
    p "USER_ADD"
    p params
    @user = User.new
    p "-" * 50
  end

 def user_new
  p"<" * 50
  p "USER_NEW"

  # si en los parametros existe un "authenticity_token", significa que el boton "Cagar pago a este usuario" ha sido clickeado
  if params.has_key?(:authenticity_token)
    p "User admin"
     @user_admin = User.new(name: params[:user][:name], email: params[:user][:email], rol: "creador de reservacion")
     if @user_admin.valid?
       if User.where(name: @user_admin.name).count == 0
         p "salvo el admin"
         @user_admin.save
         UserBooking.create!(user_id: @user_admin.id, booking_id: $booking.id)
       else
         p "actualizo"
         @user_admin = User.find_by(name: @user_admin.name)
         @user_admin.update(rol: "passenger")
       end
       @passengers =  Booking.last.users
       Flight.find($flight.id).update(total_seats: ($flight.total_seats-$seats))
       @flight = $flight
       @booking = $booking
      #  actualmentel renderiza user_new.html.erb
     else
       p "error de validacion"
        @booking = $booking
        @seats_selected = $seats
        @flight_seleceted = $flight
        @booking_users =  Booking.last.users

        render "users_in_booking.html.erb"
     end
   else
     p "User passenger"
     @user = User.new(name: params[:user][:name], email: params[:user][:email], rol: "passenger")
     if @user.valid?
       @user.save
       @user_booking = UserBooking.create!(user_id: @user.id, booking_id: $booking.id)
       UserFlight.create!(user_id: @user.id, flight_id: $flight.id)
       @booking_users =  Booking.last.users
     end
  end

  p"<" * 50
 end

 def pay
  p"<" * 50
  p "PAY"
  @user_admin = User.new
  @flight = $flight
  @seats = $seats
  # p params
  #=> <ActionController::Parameters {"controller"=>"flights", "action"=>"pay"} permitted: false>
   p"<" * 50
 end

 # def user_admin
 #   p ":" * 50
 #   p "USER_ADMIN"
 #   p ":" * 50
 # end


  private
    def flight_params
      params.require(:flight).permit(:total_seats, :destiny, :origin, :depart, :cost)
    end
end

app/controllers/user_bookings_controller.rb
class UserBookingsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/user_bookings_helper.rb
module UserBookingsHelper
end

app/views/flights/_form.html.erb
<p>compra boletos</p>
      <!-- formulario para la ruta  post "/"  que usa el metodo 'flights#show' con el alias 'forma'  -->
      <!-- remote true se encaraga de render show.js y _show.html-->
      <%=form_for forma_path, remote: true  do |f|%>
        <%@flights_origins = []%>
        <%@flights_destinys = []%>
        <%@flights_total_seats = []%>
        <!-- recolectar destinos y origenes de vuelos -->
        <%@fligths.collect do |f|%>
            <%@flights_origins << f.origin %>
            <%@flights_destinys << f.destiny %>
            <%@flights_total_seats << f.total_seats %>
        <%end%>
        <!-- eliminar origenes y destinos repetidos -->
        <%@flights_origins.uniq!%>
        <%@flights_destinys.uniq!%>
        <%@flights_total_seats.uniq!%>
        <br>
          Origen
            <!-- menu dropdown, donde el parametro seleccionado se llama 'flow' y dentro esta el hash "flight_origin"-->
            <!-- recolectamos todos los vuelos y la opcion seleccionada es el param "flight_origin" -->
            <%=select(:flow, "flight_origin", @flights_origins.collect {|origen|  origen  }, {include_blank: 'None'})%>
          <br>
          Destino
            <%=select(:flow, "flight_destiny", @flights_destinys.collect {|destino| destino }, {include_blank: 'None'})%>
          <br>
          Fecha
          <br>
          <%=date_select(:calendar, :date)%>
          <br>
            <%all_seats = @flights_total_seats.sort.last%>
            <%@flights_total_seats = []%>
            <%for seat in 1..all_seats%>
              <%@flights_total_seats << seat%>
            <%end%>
            Select seats
            <%=select(:flow , "seats_selected", @flights_total_seats.each_with_index {|v| v}, {include_blank: 'None'})%>
          <br>
          <%= f.submit "Buscar"%>
      <%end%>

app/views/flights/_pay.html.erb
<p>_pay</p>
<div class="modal-dialog">
  <div class="modal-content">

      <h2>La informacion de tu compra es</h2>


                <table class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID de vuelo</th>
                      <th>&nbsp;Costo total de la compra:</th>
                      <th>Número de Boletos: </th>
                      <th>&nbsp;Costo por Boleto</th>
                      <td>&nbsp;Destiny</td>
                      <td>&nbsp;Origin</td>
                      <td>&nbsp;Depart</td>
                      <td>&nbsp;Hour</td>
                    </tr>
                  </thead>
                  <tbody >
                    <td><%=@flight.id%></td>
                    <td><%=@seats*@flight.cost%></td>
                    <td><%=@seats%></td>
                    <td>$<%=@flight.cost%></td>
                    <td><%=@flight.destiny%></td>
                    <td><%=@flight.origin%></td>
                    <td><%="#{@flight.depart.day} of #{@flight.depart.strftime('%B')} of #{@flight.depart.year}"%></td>
                    <td><%="#{@flight.depart.hour}:#{@flight.depart.min}"%></td>

                  </tbody>
                </table>



    <!-- intentamos usar para este formulario otra ruta pero siempre usaba pay_path, asi que la usamos implicitament -->
    <%=form_for @user_admin do |f|  %>
      <div class="modal-body">
        <p>Ingresa datos de usuario de compra</p>

        <span id="por-asingar">  </span>

        <ul class="errors"></ul>

            <div class="form-group">
              <%=  f.label :name, class:"control-label" %>
              <%=f.text_field :name, class: "form-control"  %>
            </div>
            <div class="form-group">
              <%=  f.label :email, class: "control-label"%>
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>

          <div class="modal-footer">
            <%= f.submit "Hacer reservacion",:user_admin => @user_admin ,class: "btn btn-primary"%>
            <%=link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
          </div>

    <% end %>
  </div>
</div>

app/views/flights/_sub_form_user_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%=form_for @user, remote: true do |f|  %>
      <div class="modal-body">
        <p>Ingresa datos de usuario</p>

        <span id="por-asingar">  </span>

        <ul class="errors"></ul>
            <div class="form-group">
              <%=  f.label :name, class:"control-label" %>
              <%=f.text_field :name, class: "form-control"  %>
            </div>
            <div class="form-group">
              <%=  f.label :email, class: "control-label"%>
              <%= f.text_field :email, class: "form-control" %>
            </div>
          </div>

          <div class="modal-footer">
            <%= f.submit "Añadir pasajero",:user => @user ,class: "btn btn-primary"%>
            <%=link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
          </div>

    <% end %>
  </div>
</div>

app/views/flights/_users_in_booking.html.erb
  <!-- <p>users_in_booking</p> -->
  
  <div class="container">
    <br>
    Usuarios agregados al Bookig <%= @booking_users.count %>

    <%@booking_users.each do |user| %>

        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>ID</th>
              <td>&nbsp;Nombre</td>
              <td>&nbsp;Email</td>
            </tr>
          </thead>
          <tbody >
            <td><%=user.id%><br></td>
            <td><%=user.name%><br></td>
            <td><%=user.email%><br></td>
          </tbody>
        </table>

    <%end%>

  </div>

app/views/flights/index.html.erb
<div class="container">
<a href="#"><h1>Vuelos Rails</h1>  </a>

  <div class="flight-index">
        <!-- renderear formulario parcial, y pasarle el local con los vuelos-->
        <%= render "form", :fligths => @fligths %>
  </div>
</div>

app/views/flights/pay.html.erb
<div class="container">
  <h2>Tu ticket de reservacion es</h2>

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>ID de vuelo</th>

        <th>&nbsp;Costo por Boleto</th>
        <td>&nbsp;Destiny</td>
        <td>&nbsp;Origin</td>
        <td>&nbsp;Depart</td>
        <td>&nbsp;Hour</td>
      </tr>
    </thead>
    <tbody >
      <td><%=$flight.id%></td>

      <td>$<%=$flight.cost%></td>
      <td><%=$flight.destiny%></td>
      <td><%=$flight.origin%></td>
      <td><%="#{$flight.depart.day} of #{$flight.depart.strftime('%B')} of #{$flight.depart.year}"%></td>
      <td><%="#{$flight.depart.hour}:#{$flight.depart.min}"%></td>

    </tbody>
  </table>

</div>

app/views/flights/select_fly.html.erb
<div class="container">

  <h2>Vuelo seleccionado</h2>
  <!-- ESTE SPAN ES UN NUMERO IMPORTANTE, NO MODIFICAR, NOA AGREGAR NADA DENTRO -->
  <span id="seats">
    <%=@seats_selected%>
  </span> Asientos por asignar
  <br>
  Boking id: <%=@booking.id%>

  <%if @flight_seleceted %>
    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>ID de vuelo</th>
          <th>Asientos disponibles</th>
          <th>&nbsp;Costo por Boleto</th>
          <td>&nbsp;Destiny</td>
          <td>&nbsp;Origin</td>
          <td>&nbsp;Depart</td>
          <td>&nbsp;Hour</td>
        </tr>
      </thead>
      <tbody >
        <td><%=@flight_seleceted.id%></td>
        <td><%=@flight_seleceted.total_seats%></td>
        <td>$<%=@flight_seleceted.cost%></td>
        <td><%=@flight_seleceted.destiny%></td>
        <td><%=@flight_seleceted.origin%></td>
        <td><%="#{@flight_seleceted.depart.day} of #{@flight_seleceted.depart.strftime('%B')} of #{@flight_seleceted.depart.year}"%></td>
        <td><%="#{@flight_seleceted.depart.hour}:#{@flight_seleceted.depart.min}"%></td>

      </tbody>
    </table>
  <%end%>

  <%= link_to "Add users", user_add_path,:method => :post ,remote: true, class: "btn btn-primary", id: "add-ussers-button" %>
  <%= link_to "Return to seleccion", "/", class: "btn", data: {dismiss: "modal"} %>
  <span id="payment">
    <!-- asigarn el total a pagar a una var -->
    <%total_to_pay = @seats_selected.to_i * @flight_seleceted.cost%>
    <%= link_to "Pay amount of $#{total_to_pay}", pay_path , :method => :post , remote: true, class: "btn btn-danger" %>
  </span>
  <!-- en este div aparece la tabla con los usuario agregados, NO BORRAR -->
  <div id="users">

  </div>
  <div id="user-modal" class="modal fade"> </div>
  <div id="pay-modal" class="modal fade"> </div>

  
</div>

app/views/flights/select_fly.js.erb
$("#flight-modal").html("<%= escape_javascript(render 'select_fly') %>")
$("#flight-modal").modal("show")

app/views/flights/show.html.erb
<%@flight.each do |f|%>

  Origen: <%=f.origin%>
  <br>
  Destino: <%=f.destiny%>
  <br>
  Total de asientos: <%=f.total_seats%>
  <p>Fecha</p>
  Año: <%=f.time.year%>
  <br>
  Mes: <%= f.time.strftime('%B')%>
  <br>
  Dia: <%=f.time.day%>
  <br>
  Hora: <%=f.time.hour%>
  <br>
  Minutos: <%=f.time.min%>

<%end%>

app/views/flights/show.js.erb
// $(".flight-index").html("<%= escape_javascript(render 'show') %>")
$('.flight-index').html('<%= j render("show")  %>');
// $(".flight-index").modal("show")

app/views/flights/user_add.js.erb
//console.log("user_add.js");
// get the contente of the span and asign it to tha var $seats
//cabe mencionar que este contenido es un numero que es alterado por user_new.js.erb
$seats = $("#seats").html();
// si los asientos son distintos de cero
if ($seats != 0) {
  $("#user-modal").html("<%= escape_javascript(render 'sub_form_user_new') %>")
  $("#user-modal").modal("show")
}

app/views/flights/user_new.html.erb
<h2>Excelente su reservacion ha sido realizada con exito</h2>
<h3>los datos de su reseracion son los siguientes</h3>
<div class="container">
  <h4>Nombre: <%=@user_admin.name %> </h4>
  <h4>Correo: <%=@user_admin.email %></h4>
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>ID de vuelo</th>
        <th>ID de reservacion</th>
        <th>&nbsp;Costo por Boleto</th>
        <td>&nbsp;Destiny</td>
        <td>&nbsp;Origin</td>
        <td>&nbsp;Depart</td>
        <td>&nbsp;Hour</td>
        <td>&nbsp;Passenger</td>
        <%@passengers.each_with_index do |passenger, index|  %>
            <% if passenger.rol == "creador de reservacion" %>
                  <td>&nbsp;Quién hizo la reservacion</td>
            <% end %>
        <%end%>
      </tr>
    </thead>
    <tbody >
      <td><%=@flight.id%></td>
      <td><%=@booking.id%></td>
      <td>$<%=@flight.cost%></td>
      <td><%=@flight.destiny%></td>
      <td><%=@flight.origin%></td>
      <td><%="#{@flight.depart.day} of #{@flight.depart.strftime('%B')} of #{@flight.depart.year}"%></td>
      <td><%="#{@flight.depart.hour}:#{@flight.depart.min}"%></td>

      <td>
        <%@passengers.each_with_index do |passenger, index|  %>
            <% if passenger.rol == "passenger" %>

                  User:<%=index + 1%>)
                  <ul>
                    <li>Name: <%=passenger.name%></li>
                    <li>Correo: <%=passenger.email%></li>
                  </ul>

            <% end %>
        <%end%>
      </td>
      <td>
        <%@passengers.each_with_index do |passenger, index|  %>
            <% if passenger.rol == "creador de reservacion" %>
              
                  <%@passengers.each_with_index do |passenger, index|  %>
                  <% if passenger.rol != "passenger" %>


                  <ul>
                    <li>Name: <%=passenger.name%></li>
                    <li>Correo: <%=passenger.email%></li>
                  </ul>

                  <% end %>
                  <%end%>

            <% end %>
        <%end%>
      </td>

    </tbody>
  </table>
    <%= link_to "Return to seleccion de vuelos", "/", class: "btn", data: {dismiss: "modal"} %>
</div>

app/views/flights/user_new.js.erb
console.log("user_new.js.erb");
//traer el numero de @seats_selected en la vista select_fly
$seats = $("#seats").html();

//funcion para traer alterar @seats_selected, pluralizar, limpiar inputs de formulario
function modal() {
  // limpiar el underline list
  $("ul.errors").html("")
  // si emergue un error en las validaciones
  <% if @user.errors.any? %>
  // iterar en los errores
    <% @user.errors.full_messages.each do |message| %>
      //  anexar un list item con el error en cuestion
      $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
      //resetear los inputs del formulario
    <% end %>

  // en caso de no haber errores
  <% else %>

      //SI el id del span "#seats" es mayor a uno
          if ($seats > 1) {
            //resutarle uno
            $seats = $seats - 1
            //singularisacion en caso de que sólo falte por agregar un usuario
            if ($seats == 1) {
              $("#por-asingar").html("<p>Quedan por  agregar: "+ $seats +" usuario </p>")

            }else {
              // pluralizacion en caso de que falte mas de un usuario por agregar
              $("#por-asingar").html("<p>Quedan por  agregar: "+ $seats +" usarios </p>")
            };
            // set the contente of the span with the new value of seats and asign it to tha var $seats
            $seats = $("#seats").html($seats);
            //resetear los inputs del formulario
            $("#new_user")[0].reset();

            //DESCOMENTAR AL FINAL
            //alert("Objetos usuario creado");


            // cuando %seats sea igual 1
          }else {
            //restar uno
            $seats = $seats - 1
            // set the contente of the span with the new value of seats and asign it to tha var $seats
            $seats = $("#seats").html($seats);
            //en vista select_fly, en div #users, se renderea vista parcial "users_in_booking"
            $('#users').html('<%= j render("users_in_booking")  %>');

            //DESCOMENTAR ALERT
            //alert("Ultimo objeto usuario creado");
            //aparecer el boton de pagar
            $('#payment').toggle();
            //ocultar boton para añadir users
            $('#add-ussers-button').hide();

            //cerrar vista modal para agregar users
            $("#user-modal").modal('toggle');
            //id="user-modal" class="modal fade"
          }


  <% end %>


}


modal();

console.log("--------------");

//PARA ESCONDER EL FORMULARIO
// $("form").click(function() {
//   $(this).hide();
// });


//PARA APARECE UNA ALERTA POR CLICK
// $("form").click(function() {
//   var myClass = $(this).attr("id");
//   alert(myClass);
//   console.log(myClass);
// });

app/views/flights/users_in_booking.html.erb
<h2>Hay errores en los datos del usuario que hace la reservacion</h2>
<%@user_admin.errors.full_messages.each do |message| %>
   <ul>
     <li id="error"><%=message%></li>
   </ul>
 <%end %>
Boking id: <%=@booking.id%>
<% if @booking_users %>
  <%=render "users_in_booking.html.erb"%>
<%end%>
<!-- asigarn el total a pagar a una var -->
<%= link_to "Return to seleccion", "/", class: "btn", data: {dismiss: "modal"} %>
<%total_to_pay = @seats_selected.to_i * @flight_seleceted.cost%>
<%= link_to "Pay amount of $#{total_to_pay}", pay_path , :method => :post , remote: true, class: "btn btn-danger" %>

<div id="user-modal" class="modal fade"> </div>
<div id="pay-modal" class="modal fade"> </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fligths</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--AGREGAMOS ESTOS 2  -->
    <!-- <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>I -->
  </head>

  <body>
    <%= yield %>
  </body>
</html>